name: Build and upload

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.VULTR_CR_USERNAME }}
          password: ${{ secrets.VULTR_CR_PASSWORD }}
          registry: https://ams.vultrcr.com/experiences
          repository: acme-webhook-external-dns/acme-webhook-external-dns
          tags: latest

